### PR TITLE
Attempted fix on branch

### PR DESCRIPTION
**Pull request by Chasewhip8**
PLEASE review this before a merge
I was having a lot of trouble fixing my mistake with git and tons of errors in every way.
This should make merging with master fine as it should be master.

### CODE REVIEW

**Comment by T4shf33n** [comment]
The new updates of the debs should still be visible. Isn’t it? Like 590bytes were added to lzma

**Comment by Chasewhip8** [comment]
wait I did it wrong dont merge this
what I did was the rebase command was not working
so I did a pull from master and did a reset on the readme, but now that i think of it the screenshots did not get reset

**Comment by Chasewhip8** [comment]
Ok recheck this, should be able to merge with master of pwn's without a problem

**Comment by T4shf33n** [comment]
This looks better...

**Comment by T4shf33n** [comment]
I will wait for a little as I am too sleepy 🙂 and review it

**Pull request merged**
